==== Califas of Athens
Califas is an old Kindred, so old he swears Diogenes of Sinope was his mentor 
while a Human but this is doubtful since he never had any pupils per say. 

Califas is a reasonable Malkavian and speaks truth more often than most Kindred 
would, most Kindred are also more afraid than disgusted by Califas since he has 
spoken of also being alive when Antediluvians walked the Earth but this again 
is seen as another one of his delusions due to his age.

He functions as a sort of Jester in Court now that Odo has reached his position 
as Prince but his indiscretion has finally reached him with the Ventrue Primogen 
requesting justice for what has transpired and Odo following with his demands 
pointing out that Califas is a known Diabolist and Diablerist who has been let 
go of his crimes due to his service to the Camarilla and surprisingly managing 
to uphold the Masquerade even when most would not be able to.

Califas will simply move on, it would not be the first or last he does this, 
a bloodhunt will not put a stop on him and neither will a Justicar.

