==== Antonio Bartolomeo Lazaro di Genoa (Lazathiel)
A merchant of Genoa who has a fair share of the market of Genoa, he is known 
to be a ruthless trader and hold a personal army that could currently put the 
one on Venice to shame, Alberto will come to Genoa personally to put more 
strain into their situation and personally verify that the Giovanni show some 
retrain on what they are doing and to learn their place in this century in 
which Venice is fading.

Lazaro has already tried to tempt the Ventrue PC into his service but he has 
failed to bring him to his side with power, Lazaro will continue to pursue 
Kindred of the Camarilla to his side in order to bring them into disarray and 
for his plans to come into fruition.

Should the players try to challenge or fight Alberto they will find a Fallen of 
much more power than any of the Kindred in Venice or any Fallen for that matter, 
Lazathiel is a Fallen who absolutely despises Devils and will go into any extent 
to absorb them, he will never allow them to go back to the Abyss, he cares 
little for Kindred and considers them a nuisance which he will remove with 
easiness if he is bothered. He is a Faustian to the extreme, he has little 
regards for Humans and will fight to get to God and end the fight that the 
traitor Lucifer did not finish to sit on the High Throne from which he can 
supervise the creation of a New World of darkness.

