== Duke Emil of Caen and Duke Rodolfo of Flanders

Emil is one of several brothers who were embraced to sustain power for a 
dying family, little did they know the mistake of such act.

Emil and his brother Rodolfo were both Sired by the same Kindred, who in 
turn they diablerized and so they did with others in the region in order 
to gain power and titles, with a large number of Ghouls under their command 
it was to no surprise that they managed to also obtain Fiefdoms although the 
feat by William the Bastard escaped them during their early days, and they do 
not forgive themselves for letting go of such possessions, they continue to 
look for ways to expand the power of Paris and France throughout Europe 
through any means necessary which originally included the death of the Prince 
of Venice, a long friend of both of them who had also conspired from time to 
time to get to where they were and in a way was assisted by both brothers to 
reach Venice, who saw his Final Death before they could put their plan into action.

Due to their actions Emil and Rodolfo have escaped Venice and by political 
maneuvering are now marked for bloodhunt due to their conspiration to destabilize 
the Camarilla and murdering the former Prince of Venice, this coupled with 
previous actions has also put them on a bloodhunt in Paris by the Prince of such 
Domain, their flight may not save them in time.

Emil has Sired a trader of fine leathers in Venice, a PC for the Campaign, 
while Rodolfo has a Childer back in his dominion who watches over as he is away, 
which is most of the time.

