== Francesca (Lucretia)
Odo is the only one that truly understands what transpired with her Embrace, 
she is a twelve year old who was delivered to the Monastery in which he 
resides in Verona and to his surprise found out that she was a Kindred just 
as him, he was also surprised to find that she could write, read and 
understand him perfectly but would not speak to him, throughout the years 
Francesca, as she calls herself, has been an aide for Odo on situations that 
he is unable to intervene. Odo is unaware what Clan she is part of and other 
Kindred do not interact with her, it is hard already to interact with other 
Kindreds but a Child is not one to be delivered into the World of Darkness 
for no good reason.

During his tenure as Prince, Odo will come to learn that Francesca, who is 
also known as Lucretia, was raped by a Kindred and his Ghouls and embraced 
in what could be considered a spur of the moment, being a survivor of this 
event she drained one of the ghouls and killed another, from there on she 
continued to escape until she was found by inhabitants in Verona and taken 
to Odo. Odo will also come to learn that the Sire of Francesca is a Follower 
of Set and has a very large group of ghouls and retainers that will assist 
him in every possible way to continue his task, Francesca does not manifest 
the disciplines she has not because she does not want to but because she is 
afraid of the unwillingly earned powers of her Sire.

Francesca made it to Venice after being informed that Odo had moved out from 
Verona, not wishing to lose contact with him she proceeded to Venice on her 
own only to find herself lost in the vast city, it was due to player 
interaction that they found her although by slight accident. Delivering her to 
Odo and with the help of Emmanuel they managed to understand what happened to 
her, Odo has made it known that those responsible will be hunted.

