== Renee Ferdinand Antoine
Renee is a Mage who finds himself in a troubled position, he became one due 
to his interest in the Occult and then regretted it the rest of his life, 
seeing more than the fair share of people die in his short life he has 
dedicated his life to write about those he wishes not forgotten, including 
himself, frustrated by his lack of abilities he writes what he can as he does 
what he must to survive, an admirable alchemist and a mediocre Doctor when no 
one else is available for the job.

While younger Renee dedicated himself to pickpocketing and lockpicking to 
survive, this way of life led him to many problems but also to think more 
about what he wished in life, he did not believe himself capable of attaining 
a high enough status to survive this life. One of his many adventures led him 
to discover a book of the Occult, from there on he dedicated to learn and 
understand more about this venue and eventually found himself in touch with 
others who shared his interest, in time he was invited to be part of something 
bigger than him.

Renee is a dedicated Demonologist and his task is to investigate possible uses 
and abuses of connections with the Devil or other demons, while he does not 
work with the Church directly or the Inquisition his interest is due to his 
understanding that the Tremere Clan formed a pact with the devil that delivered 
the terrible power they hold now.

He is aware about the intentions of the Lasombra of Venice and whilst interested 
in the Occult he is not one to deal openly with them, earning the wrath of his 
fellow Mage and Kindred would bring him death fairly quickly. This does not mean 
he does not wish to do so, simply that he needs to choose how and when with more 
care than.

