==== Seneschal Emmanuel de Ponce y Ramirez
Emmanuel is a Kindred to be recognized and feared, ruthless, calculating, a 
political and economical powerhouse on his own, owner of a large majority of 
mercenaries of Venice and of his own island on the outskirts of Venice, 
controls one of the offices of Venice and owns a personal fleet of twenty 
boats which he uses to defend and trade around the coast of Italy.

Emmanuel has never trusted the Camarilla Ventrue for being naturally 
incompetent in his eyes, had it not been the case Venice would not be of the 
Giovanni and the Giovanni would not exist at all, he does not blame the Sabbat 
for they never really cared for Venice and are too busy trying to kill 
anything that moves to even bother with more important things like stopping 
the Jyhad or obtaining the Fragments in order to understand the truth about Caine.

He does not have a good relationship with the other Lasombra and they do not 
like him either but stand him because of the magnitude of his power, when he 
visited Odo to understand what had transpired and how was he ever elected 
Prince he was informed that the position of Seneschal had been given to him and 
that his first appearance in Court would be an absolute delight to the Ventrue. 

With this Emmanuel has put a small amount of fate in the Camarilla and has 
become indebted with Odo for the rest of his unlife for this favor, one that he 
may end up paying costly.

Emmanuel is a practicioner of the Occult long before he joined the ranks of 
Lasombra, a man of power and knowledge who held large estates both in Italy and 
what is now Spain, his signature Estate is outside of Venice for good reason, 
it gives him somewhere to stay away from the rest of the rabble and he can 
continue to practice and investigate further on

Rumor has it that Emmanuel possesses a large collection of crosses which includes 
parts of the cross in which Christ was crucified, also rumored that he has in 
his hands parts of the remains of Saint Peter but Ricardo considers that to be 
an exaggeration but knowing how Catholic Emmanuel is he does not have any doubt 
that he could have been scammed out of his beliefs.

