==== Sheriff of Venice, Don Ricardo de Castilla
Considered by many as an undesirable amongst the Kindred of the Camarilla, a 
traitor by the Sabbat and non-existent by Lasombra and the Amis de Noir, 
Ricardo stands with his friend Odo and not with any faction. 

While an antitribu he committed many acts of diablerie (Amaranth) throughout 
his un-life and thus has more aces under his sleeves than most would think or 
assume, he is resourceful, cunning, has a quick tongue and a quicker hand, 
fair with his peers as he always remembers where he came from, he has not 
achieved as much as he would have liked due to the structure of the Camarilla 
but in the long run he does not mind, he is a dilettante by nature and thus 
makes many calls on who is and who is not hot, this has earned the disgust 
of Emmanuel, a “fellow” Lasombra antitribu that holds considerable political 
and economic power in Venice.

Ricardo, as Odo, are well known throughout Europe and infamous for their antics 
in the past, they cover for each other when possible and provide when needed, 
Ricardo has Sired twice through his un-life, the first a young maiden which met 
her demise rather quickly and left him with a sense of guilt for not being 
responsible enough, from there on he lost himself to the pleasures and lust of life. 

His second Childer has faired better but stands in the Sabbath instead of the 
Camarilla, Manuel de Cerdena is a Kindred of little renown and more of a hindrance 
to his Sire than of actual use but in times of needs has proved to be as resourceful 
as his Sire.

Ricardo works as a father figure for Neonates as he never truly had one when 
growing up during the middle ages or after being embraced.

