==== Lucius Quintus Scipio (Fabriccio)
Quintus, as referred to by fellow Toreador, is a man with true potential in 
regards to drawing and designing, a fanatic of numbers and equations, he 
indulges in simple vices just to keep his mind entertained and avoid taking 
suicide into consideration again. He works odd jobs throughout Venice, he may 
produce a sketch for someone in the street and just give it to them for free, 
he may make the design for a house and rip it apart, he may make a map just 
to learn the name of cities and towns, whatever fits the moment is what he 
does if he ever finds what fits the moment.

Quintus has established a relation with a PC to create a sort of house for 
designers, taking to life some of his designs for the first time ever which 
has drawn approval from the local Toreador, specially since he has been given 
a formal job by the PC as his designed for leather.

After Quintus learned that the Osprey, Duke of Orleans, was in Venice he 
decided to make flight back to Paris while apologizing to the rest of the 
Toreador in the city.

