==== (Old) Odo, the Bishop of Verona, future Cardinal of Venice, Prince of Venice
Odo is a Toreador that has lived since the Middle Ages, he comes from a lowborn 
background and fought his way up, during his mortal life he became aware of the 
Kindred by accident by helping a Nosferatu who he thought was a leper, later on 
he would continue to assist the Nosferatu as he served as a Clergyman for the 
Church trying to repent for his bloodshed during the 1st Crusade as he never 
accepted it as a form of redemption in the eyes of God, to him all are equal to 
God and the amount of blood shed can in no way or form please such a God. Odo 
was embraced in his mid-thirties by a Toreador who considered him an excellent 
asset for their Clan as Odo, while a Clergyman, had considerable good taste 
and was a safe keeper and patron of the Arts when he could afford such a thing.

Odo is fair but cruel with Humans in general, he sees them no as no more than 
cattle and as broken vessels who deserve nothing but the full wrath of God for 
their little to no understanding of the reality of life, he does not share this 
feeling with his fellow Kindred as the Camarilla has showed him that certain 
restrain is possible and thus despises the Sabbath line of thought and anyone 
working directly with them.

Odo has a long standing feud with some of the NPCs showed during the campaign, 
Emil of Caen and Rodolfo of Flanders are two prime examples, the former Prince 
Alberto of Venice was another example as he lived in pure excess and rampant 
luxury Odo decided not to present himself to court even when the Prince himself 
demanded such a thing. 

Maximilian Ferdinand of Cologne stands in a middle ground with Odo and so do 
the Giovanni who keep their claim of Venice and have demanded for the Camarilla 
and Sabbat to stop their incursions in Venice, specially through the Promise 
of 1528 (keyword: Promise) that the Camarilla and the Giovanni accorded. 
Califas of Athens is another Kindred, a Malkavian, with whom he has a middle 
grounded stance, while he does not treat them as others would he is not found 
of him, he needs him even if his predictions are esoteric and hardly ever make 
sense to the Kindred around him but nonetheless Odo has found that the 
prediction of Venice burning in at least 100 years is a probable accurate 
prediction with the way things are going.

He is in considerable good standing with the Nosferatu of Venice through their 
Primogen Bel Antonio de Florence and with his long-time friend Ricardo de 
Castilla. Odo is in such good standing because he saved a Nosferatu during his 
time as Priest thinking he was a leper, later on he was informed of what the 
Kindred were and their curse, from there on Odo searched for a way to help the 
Kindred redeem and go with God but seeing his life was already at the end of 
its leash he turned to a Toreador which embraced him to allow him to continue 
his work as a Kindred.

While this surprised many who knew him the Nosferatu were openly shocked by 
his decision, not that they wished to embrace him but were disappointed that 
they did not follow the warning provided by them in regards to Kindred society.

Odo has previously been in the first Crusade with Ricardo but renounced the 
supposed salvation this could have brought him as the bloodshed disgusted him 
and considered it not to be the proper way to be in the good side of God, thus 
he turned to the Church to find salvation and help others also find salvation 
although disappointment reached him during his unlife as he understood the true 
ways of the Vatican and who really controls the power behind the scene.

He and Ricardo have a long history, while they were both there for each other 
Odo has never forgiven himself for not being able to help his best friend in his 
time of most need and although Odo stood with the Camarilla and Ricardo went 
with the Sabbat it was the latter that decided to return to the Camarilla in 
order to be with his best friend and also it was Odo who assisted him during 
this time in which no one would trust him.

At this point Odo stands as the legitimate Prince of Venice due to the untimely 
and horrible death of former Prince Alberto of Venice, he does so by having a 
charter provided to him by the Nosferatu who had kept it under their watch for 
the last 300 years that the Camarilla had continuously seen Princes change 
inside Venice. Odo has also sent to Rome his letter asking for a position as 
Cardinal. Odo had also Sired a Kindred a week prior to the events that 
unfolded, his Childer is a PC of this Campaign.

