==== Osprey, Duke of Orleans
The Duke of Orleans has been there since the beginning of France, he is the 
figure responsible for bringing the entirety of France into what it is now 
today, through political intrigue and manipulation he has managed to push a 
squabbling nation into one of the main players of the current politics of 
Europe and the world.

This has not come without consequences, Osprey, while a Toreador, did not 
envision the Camarilla as the answer the Kindred needed for their situation, 
specially since he had conspired for the Church to burn some of his enemies. 

Making the obvious jump Osprey went to the Sabbat were he figured he could 
earn the respect and power he deserved, having earned little power yet plenty 
of recognition for what he had achieved.

The Sabbat was indifferent to what Osprey had performed, he had to not only 
prove himself to them but also help them fight the Camarilla and the Jyhad, 
which Osprey suspected was more of a way to keep things under control than 
an actual fight, a fight against Elders and things he had never seen but 
in a way had felt throughout his time in France.

In Venice he is looking to prove himself by putting the Sabbat in control of 
the city or die in the process, he has gone through enough to fail, going to 
the Camarilla would probably earn him a quick death and going back to the 
Sabbat empty handed would mean becoming the play thing of a Tzimisce.

