==== Elim
An inhabitant of the wild since his early life, living with a family dedicated 
to farming work and rising cattle. It was during one of his adventures on the 
outside that he found himself followed by a Gangrel who had been keeping an 
eye on him for some time, the Embrace happened faster than Elim could have 
noticed and with it a week of confusion and rejection from Childer to Sire.

Elim was torn, he wished to see his family again but finding his Kindred 
status making this an impossible feat he moved to the city of Venice to his 
Sire surprise and disappointment. Intrigued by the way of the city and 
civilization it has been a continuos task to keep educating and growing in 
the eyes of his fellow Kindred, looking not for acceptance but to be the 
opposite of what he was forced to be. He walks into the café of the Toreador 
in order to learn from them and be up to date in city and Camarilla politics.

Story wise Elim was the son of the man who delivered goods to the PC who is 
the Merchant of Leather of Venice, he may recall him at one point if he sees 
him and Elim will immediately recognize him.

